export const rules = {
  Standard: [
    '2 = You (choose someone to drink)',
    '3 = Me (you drink)',
    '4 = Floor (everyone touches the floor, last one to do so drinks)',
    '5 = Guys (all guys drink)',
    '6 = Chicks (all girls drink)',
    '7 = Heaven (point to the sky, last one to do so drinks)',
    '8 = Mate (choose someone to drink with you)',
    '9 = Rhyme (choose a word, everyone has to say a word that rhymes with it, first one who can\'t drink)',
    '10 = Categories (choose a category, everyone has to name something from that category, first one who can\'t drink)',
    'Jack = Make a rule',
    'Queen = Question Master (if you answer a question asked by the question master, you drink)',
    'King = Pour (pour some of your drink into the center cup, the person who draws the last king has to drink it)',
    'Ace = Waterfall (everyone starts drinking at the same time, and no one can stop until the person to their right stops)',
  ],
  Extreme: [
    '2 = You (choose someone to drink double)',
    '3 = Me (you drink triple)',
    '4 = Floor (everyone touches the floor, last one to do so drinks half their drink)',
    '5 = Guys (all guys drink, then they have to spin around 5 times before they stop drinking)',
    '6 = Chicks (all girls drink, then they have to do 6 push-ups before they stop drinking)',
    '7 = Heaven (point to the sky, last one to do so drinks, then they have to hold one arm up for 7 seconds)',
    '8 = Mate (choose someone to drink with you, but you both have to drink with your non-dominant hand)',
    '9 = Rhyme (choose a word, everyone has to say a word that rhymes with it, first one who can\'t drink for 9 seconds)',
    '10 = Categories (choose a category, everyone has to name something from that category, first one who can\'t drink for 10 seconds)',
    'Jack = Thumb Master (whenever you place your thumb on the table, all other players must do the same, last one to do so drinks, then they have to place their thumb on the table again)',
    'Queen = Question Master (if you answer a question asked by the question master, you drink, then you have to answer another question asked by the question master)',
    'King = Pour (pour some of your drink into the center cup, the person who draws the last king has to drink it, then they have to pour the rest of their drink into the center cup)',
    'Ace = Make a rule (come up with a rule that all players must follow, anyone who breaks the rule drinks, then they have to follow two more rules made by other players)',
  ],  
};
