export const rules = {
  Standard: [
    '2 = You (choose someone to drink)',
    '3 = Me (you drink)',
    '4 = Whores (all girls drink)',
    '5 = Dive (Last one to touch the floor drinks)',
    '6 = Dicks {all guys drink)',
    '7 = Heaven (point to the sky, last one to do so drinks)',
    '8 = Mate (choose someone to drink with you)',
    '9 = Rhyme (choose a word, everyone has to say a word that rhymes with it, first one who can\'t drink)',
    '10 = Categories (choose a category, everyone has to name something from that category, first one who can\'t drink)',
    'Jack = Make a rule',
    'Queen = Question Master (if you answer a question asked by the question master, you drink)',
    'King = Pour (pour some of your drink into the center cup, the person who draws the last king has to drink it)',
    'Ace = Waterfall (everyone starts drinking at the same time, and no one can stop until the person to their right stops)',
  ],
  Extreme: [
    '2 = Double You (choose two people to drink)',
    '3 = Triple Me (you drink three times)',
    '4 = Whores War (all girls have a thumb war, loser drinks)',
    '5 = Dance-off (all girls have a dance-off, loser drinks)',
    '6 = Dicks Duel (all guys have a thumb war, loser drinks)',
    '7 = Hell (everyone chugs their drink, last one to finish drinks again)',
    '8 = Fate (choose someone to drink with you, then both swap seats)',
    '9 = Mime (choose a word, everyone has to act it out, first one who cant drink)',
    '10 = Double Categories (choose two categories, everyone has to name something from both, first one who cant drink)',
    'Jack = Make a rule and everyone takes a shot',
    'Queen = Quiz Master (ask a trivia question, first one to answer incorrectly drinks)',
    'King = Pour & Spin (pour some of your drink into the center cup, then spin a bottle, whoever it points to drinks the cup)',
    'Ace = Reverse Waterfall (same as waterfall, but in reverse order)',
  ],
  Fun: [
    '2 = Truth or Drink (choose someone, they must either answer a truth question or drink)',
    '3 = Me Three (you do three push-ups or drink)',
    '4 = High Four (everyone high fives the person to their left, last one to do so drinks)',
    '5 = Jive (everyone does a silly dance, person with the worst dance drinks)',
    '6 = Pick-up Sticks (all guys try to pick up something using only their feet, first to fail drinks)',
    '7 = Swap Heaven (swap seats with the person to your left)',
    '8 = Blind Date (choose someone to wear a blindfold, then they must guess who is speaking or drink)',
    '9 = Bust a Rhyme (choose a word, everyone raps a line that rhymes with it, first one who cant drink)',
    '10 = Super Categories (choose a category, everyone has to name something from that category while doing a handstand, first one who cant drink)',
    'Jack = Act a Scene (act out a scene from a movie, everyone else guesses the movie, first one to guess correctly makes someone drink)',
    'Queen = Royal Roast (everyone roasts the person to their right, best roast chooses someone to drink)',
    'King = Kings Court (pour some of your drink into the center cup, person who draws the last king must perform a dare or drink the cup)',
    'Ace = Race (everyone races to finish their drink, first one done chooses someone to refill their drink and drink it)',
  ],
  Weed_Edition:
    [
      '2 = Toke (choose someone to take a hit)',
      '3 = Me (you take a hit)',
      '4 = Pass (pass the joint to the person to your left)',
      '5 = High 5 (last one to give a high five drinks)',
      '6 = Doobie Brothers (all guys take a hit)',
      '7 = Heaven (point to the sky, last one to do so takes a hit)',
      '8 = Share (choose someone to take a hit with you)',
      '9 = Categories (choose a category, everyone has to name something from that category, first one who cant take a hit) ',
'10 = Never Have I Ever (say something you havent done, everyone who has done it takes a hit) ',
'Jack = Roll a Joint',
      'Queen = Question Master (if you answer a question asked by the question master, you take a hit)',
      'King = Pour (pour some of your drink into the center cup, the person who draws the last king has to take a hit)',
      'Ace = Bong Hit (everyone takes a hit at the same time, and no one can stop until the person to their right stops)'
    ],
    Balanced: [
    '2 = Share (choose someone to drink with you)',
    '3 = Trivia (answer a trivia question, if you get it wrong, drink)',
    '4 = Encore (everyone sings a line from a song, first one who can\'t think of a line drinks)',
    '5 = High Five (everyone high fives the person to their left, last one to do so drinks)',
    '6 = Story Time (all guys take turns adding a line to a story, first one who can\'t continue the story drinks)',
    '7 = Compliment (give a compliment to the person on your left, if its not genuine, drink)',
    '8 = Switch (swap seats with someone)',
    '9 = Word Chain (choose a word, everyone has to say a word that starts with the last letter of the previous word, first one who can\'t drink)',
    '10 = Two Truths and a Lie (say two truths and one lie about yourself, if someone guesses the lie, they choose someone to drink, otherwise you drink)',
    'Jack = Talent Show (perform a talent, if people are not impressed, drink)',
    'Queen = Confession (share an embarrassing story or drink)',
    'King = Pour (pour some of your drink into the center cup, the person who draws the last king has to drink it)',
    'Ace = Cheers (everyone toasts and takes a drink together)',
  ],
  Active: [
    '2 = Drink & Dare (choose someone to drink, then give them a dare)',
    '3 = Me & Three (you drink and do three jumping jacks)',
    '4 = Whores Wars (all girls have a staring contest, loser drinks)',
    '5 = Torture Trivia (ask a trivia question, the first person to answer incorrectly drinks twice)',
    '6 = Dicks Debacle (all guys have a push-up contest, loser drinks)',
    '7 = Drinking Jenga (stack cups on top of each other, first one to knock the tower over drinks)',
    '8 = Double Trouble (choose someone to drink and swap seats with them)',
    '9 = Boozy Charades (choose a word or phrase, everyone has to act it out, first one who can\'t drink)',
    '10 = Punishment Plank (choose a category, everyone has to name something from that category while holding a plank, first one who can\'t drink)',
    'Jack = Royal Decree (make a rule, then take a shot)',
    'Queen = Interrogation (ask a series of questions to a person, if they refuse to answer or lie, they drink)',
    'King = Kings Demise (pour some of your drink into the center cup, person who draws the last king must chug the cup and do a silly dance)',
    'Ace = All-out Assault (everyone chugs their drink and does a silly dance, the last one to finish drinks again)',
  ],
};